package springbootrestcrudspringdatajparestemployeeremovedallboilerplatecode.springbootrestcrudspringdatajparestemployeeremovedallboilerplatecode;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringBootRestCrudSpringDataJpaRestEmployeeRemovedallboilerplatecodeApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringBootRestCrudSpringDataJpaRestEmployeeRemovedallboilerplatecodeApplication.class, args);
	}

}
